version: "3"
services:
        app:
            container_name: avcon-dockerhub-sample
            image: avimg-dockerhub-sample       
            restart: always
            build: .
            env_file: ./.env
            ports:
              - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT      
        