version: "3"
services:
        app:
            container_name: avcon-node-simple     
            image: avimg-node-simple       
            restart: always
            build: .
            ports:
              - "5000:5000"            
        